source "https://rubygems.org"

ruby "3.4.4"

gem "rake", "~> 13.0"

group :test do
  gem "rspec", "~> 3.12"
  gem "rspec-core", "~> 3.12"
  gem "rspec-expectations", "~> 3.12"
  gem "rspec-mocks", "~> 3.12"
end

group :development, :test do
  gem "rubocop", "~> 1.50"
end

gem "solargraph", "~> 0.56.1"
